CPLUSPLUS      = icpc # C++ compiler
CPLUSPLUS_MPI  = mpiicpc # intel mpi or mpich
FORTRAN       = ifort # Fortran compiler
LAPACK_DIR = $(MKLROOT) # intel mkl
FFTW_DIR       = YourPath/lib/fftw # lib fftw
BOOST_DIR      = YourPath/lib/boost # lib boost
ELPA_DIR = YourPath/lib/elpa # lib elpa
